---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: file-managed-standard-retain
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
reclaimPolicy: Retain # Currently giving an error
volumeBindingMode: WaitForFirstConsumer
#allowVolumeExpansion: "true"
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30
  #- nosharesock
parameters:
  skuName: Standard_LRS
  #protocol: nfs
---

# https://docs.microsoft.com/en-us/azure/aks/azure-files-csi
# https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv